// MERN/frontend/src/components/ProductCard/ProductCard.jsx
import React from "react";
import { Button, Card } from "antd";
import { useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";
import { ShoppingCartOutlined } from "@ant-design/icons";
import axios from "axios";

const Product = ({ product }) => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { Meta } = Card;

  const handlerToCart = async () => {
    try {
      // Verifică dacă produsul are stoc disponibil
      if (product.stock <= 0) {
        alert("Stoc epuizat!");
        return;
      }

      // Trimite cererea pentru actualizarea stocului pe server
      await axios.post("/api/products/updateStock", {
        productId: product._id,
        quantityToDecrease: 1,
      });

      // Adaugă produsul în coș
      dispatch({
        type: "ADD_TO_CART",
        payload: { ...product, quantity: 1 },
      });
    } catch (error) {
      console.error("Eroare la actualizarea stocului:", error);
    }
  };

  const handleLearnMore = () => {
    navigate(`/product/${product._id}`);
  };

  return (
    <Card
      hoverable
      style={{ width: 240, marginBottom: 30 }}
      cover={
        <img alt={product.name} src={product.image} style={{ height: 200 }} />
      }>
      <Meta title={product.name} description={`€${product.price}`} />
      <div
        className='product-btn'
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}>
        <Button onClick={handleLearnMore}>Află mai multe</Button>
        <Button
          icon={<ShoppingCartOutlined />}
          onClick={handlerToCart}
          disabled={product.stock <= 0}>
          {product.stock <= 0 ? "Stoc epuizat" : ""}
        </Button>
      </div>
    </Card>
  );
};

export default Product;

// MEAN/frontend/src/app/components/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
import { CartService } from '../../services/cart.service';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { NgIf } from '@angular/common';
import { MatIcon } from '@angular/material/icon';

export interface CartItem {
  _id: string;
  name: string;
  price: number;
  quantity: number;
  image: string;
  stock: number;
}

export interface Product {
  _id: string;
  name: string;
  image: string;
  price: number;
  category: string;
  description: string;
  stock: number;
}

@Component({
  standalone: true,
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.css'],
  imports: [MatIconModule, MatCardModule, NgIf, MatIcon],
})
export class ProductCardComponent {
  @Input() product!: Product;

  constructor(private router: Router, private cartService: CartService) {}

  handleLearnMore() {
    this.router.navigate(['/product', this.product._id]);
  }

  handleAddToCart() {
    if (this.product.stock <= 0) {
      alert('Stoc epuizat!');
      return;
    }

    this.cartService.addToCart({
      ...this.product,
      quantity: 1,
    });
    console.log('Add to cart clicked!');
  }
}

<div class="card-container">
  <div class="card">
    <img
      [src]="'/assets' + product.image"
      [alt]="product.name"
      class="card-img-top"
    />
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <p class="card-text">€{{ product.price }}</p>
      <div
        class="product-btn"
        style="display: flex; gap: 10px; align-items: center"
      >
        <button class="btn btn-primary" (click)="handleLearnMore()">
          Află mai multe
        </button>

        <button
          class="button-icon"
          (click)="handleAddToCart()"
          [disabled]="product.stock <= 0"
          title="Adaugă în coș"
          style="display: flex; align-items: center; justify-content: center"
        >
          <mat-icon class="add-to-cart-icon">shopping_cart</mat-icon>
        </button>
      </div>
      <p *ngIf="product.stock <= 0" style="color: red; margin-top: 5px">
        Stoc epuizat!
      </p>
    </div>
  </div>
</div>
