// MEAN/frontend/src/app/pages/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductService } from '../../services/product.service';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.css'],
  imports: [NgIf],
})
export class ProductDetailsComponent implements OnInit {
  product: any = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private productService: ProductService
  ) {}

  ngOnInit(): void {
    const productId = this.route.snapshot.paramMap.get('id');
    if (productId) {
      this.productService.getProductById(productId).subscribe({
        next: (data) => (this.product = data),
        error: (err) => console.error('Eroare la încărcare produs:', err),
      });
    }
  }

  goBack(): void {
    this.router.navigate(['/']);
  }
}

<section *ngIf="product; else loading">
  <div class="layout-app">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="product-content">
            <h2 class="title">Detalii produs</h2>
            <img
              [src]="'/assets' + product.image"
              [alt]="product.name"
              class="product-image"
            />
            <h3>{{ product.name }}</h3>
            <h4>€{{ product.price }}</h4>
            <p>{{ product.description }}</p>
          </div>
          <div class="button-wrapper">
            <button mat-stroked-button color="primary" (click)="goBack()">
              Înapoi
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<ng-template #loading>
  <h4 class="text-center pt-5">Loading...</h4>
</ng-template>

// MERN/frontend/src/pages/products/ProductDetails.jsx
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Container, Row, Col } from "reactstrap";
import { Button } from "antd";
import axios from "axios";
import "./ProductDetails.css";
import LayoutApp from "../../components/Layout/Layout";

const ProductDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [product, setProduct] = useState(null);

  useEffect(() => {
    const fetchProductDetails = async () => {
      try {
        const { data } = await axios.get(`/api/products/getproducts/${id}`);
        setProduct(data);
      } catch (error) {
        console.error("Error fetching product details:", error);
      }
    };

    fetchProductDetails();
  }, [id]);

  if (!product) {
    return <h4 className='text-center pt-5'>Loading...</h4>;
  }

  const { name, description, image, price } = product;

  return (
    <LayoutApp>
      <section>
        <Container>
          <Row>
            <Col lg='8'>
              <div className='product-content'>
                <h2 style={{ marginBottom: "20px" }}>Detalii produs</h2>
                <img src={image} alt={name} className='product-image' />
                <h2>{name}</h2>
                <h4>€{price}</h4>
                <p>{description}</p>
              </div>
              <div style={{ marginTop: "20px" }}>
                <Button type='default' onClick={() => navigate("/")}>
                  Înapoi
                </Button>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </LayoutApp>
  );
};
export default ProductDetails;
