// MEAN/frontend/src/app/pages/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { CartService } from '../../services/cart.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Router } from '@angular/router';
import { CommonModule, NgIf } from '@angular/common';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { ReactiveFormsModule } from '@angular/forms';
import { MatIcon, MatIconModule } from '@angular/material/icon';

export interface CartItem {
  _id: string;
  name: string;
  price: number;
  quantity: number;
  image: string;
}

@Component({
  standalone: true,
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css'],
  imports: [
    HttpClientModule,
    NgIf,
    CommonModule,
    MatTableModule,
    MatButtonModule,
    ReactiveFormsModule,
    MatIcon,
    MatIconModule,
  ],
})
export class CartComponent implements OnInit {
  cartItems: CartItem[] = [];
  subTotal = 0;
  billForm: FormGroup;
  billPopupVisible = false;

  constructor(
    private cartService: CartService,
    private fb: FormBuilder,
    private http: HttpClient,
    public router: Router
  ) {
    this.billForm = this.fb.group({
      customerName: ['', Validators.required],
      customerPhone: ['', Validators.required],
      customerAddress: ['', Validators.required],
      paymentMethod: ['', Validators.required],
    });
  }

  ngOnInit() {
    this.cartService.cartItems$.subscribe((items) => {
      this.cartItems = items;
      this.subTotal = items.reduce(
        (acc, item) => acc + item.price * item.quantity,
        0
      );
    });
  }

  increment(item: CartItem) {
    this.cartService.updateQuantity(item._id, item.quantity + 1);
  }

  decrement(item: CartItem) {
    if (item.quantity > 1) {
      this.cartService.updateQuantity(item._id, item.quantity - 1);
    }
  }

  delete(item: CartItem) {
    this.cartService.removeItem(item._id);
  }

  openBillPopup() {
    this.billPopupVisible = true;
  }

  closeBillPopup() {
    this.billPopupVisible = false;
  }

  generateBill() {
    if (this.billForm.invalid) return;

    const user = JSON.parse(localStorage.getItem('auth')!);
    if (!user?.id) {
      alert('Utilizator neautentificat.');
      return;
    }

    const tax = +(this.subTotal * 0.1).toFixed(2);
    const totalAmount = +(this.subTotal + tax).toFixed(2);

    const billData = {
      ...this.billForm.value,
      cartItems: this.cartItems,
      subTotal: this.subTotal,
      tax,
      totalAmount,
      userId: user.id,
    };

    this.http.post('/api/bills/addbills', billData).subscribe({
      next: () => {
        alert('Factură generată cu succes!');
        this.cartService.clearCart();
        this.closeBillPopup();
        this.router.navigate(
          user.role === 'admin' ? ['/bills'] : ['/your-bills']
        );
      },
      error: (err) => {
        alert(err?.error?.message || 'Eroare la generarea facturii');
      },
    });
  }
}

<div class="product-container">
  <h2 class="title">Coșul tău</h2>

  <div *ngIf="cartItems.length === 0" class="empty-cart">
    <h3>Coșul tău este gol!</h3>
    <div class="button-container">
      <button
        mat-raised-button
        color="primary"
        (click)="router.navigate(['/'])"
      >
        Mergi la produse
      </button>
    </div>
  </div>

  <div *ngIf="cartItems.length > 0">
    <table
      mat-table
      [dataSource]="cartItems"
      class="mat-elevation-z8 product-table"
    >
      <!-- Nume -->
      <ng-container matColumnDef="name">
        <th mat-header-cell *matHeaderCellDef>Nume</th>
        <td mat-cell *matCellDef="let item">{{ item.name }}</td>
      </ng-container>

      <!-- Imagine -->
      <ng-container matColumnDef="image">
        <th mat-header-cell *matHeaderCellDef>Imagine</th>
        <td mat-cell *matCellDef="let item">
          <img
            [src]="'/assets' + item.image"
            [alt]="item.name"
            width="60"
            height="60"
            style="object-fit: cover; border-radius: 4px"
          />
        </td>
      </ng-container>

      <!-- Preț -->
      <ng-container matColumnDef="price">
        <th mat-header-cell *matHeaderCellDef>Preț</th>
        <td mat-cell *matCellDef="let item">€{{ item.price }}</td>
      </ng-container>

      <!-- Cantitate -->
      <ng-container matColumnDef="quantity">
        <th mat-header-cell *matHeaderCellDef>Cantitate</th>
        <td mat-cell *matCellDef="let item">
          <button mat-icon-button color="primary" (click)="decrement(item)">
            -
          </button>
          <strong>{{ item.quantity }}</strong>
          <button mat-icon-button color="primary" (click)="increment(item)">
            +
          </button>
        </td>
      </ng-container>

      <!-- Acțiuni -->
      <ng-container matColumnDef="actions">
        <th mat-header-cell *matHeaderCellDef>Acțiune</th>
        <td mat-cell *matCellDef="let item">
          <button
            mat-icon-button
            color="warn"
            (click)="delete(item)"
            aria-label="Șterge produs din coș"
          >
            <mat-icon>delete</mat-icon>
          </button>
        </td>
      </ng-container>

      <tr
        mat-header-row
        *matHeaderRowDef="['name', 'image', 'price', 'quantity', 'actions']"
      ></tr>
      <tr
        mat-row
        *matRowDef="
          let row;
          columns: ['name', 'image', 'price', 'quantity', 'actions']
        "
      ></tr>
    </table>

    <div
      class="button-container"
      style="justify-content: flex-end; margin-top: 20px"
    >
      <h3 style="margin-right: 20px; margin-bottom: 20px">
        Subtotal: €{{ subTotal.toFixed(2) }}
      </h3>
      <button mat-raised-button color="primary" (click)="openBillPopup()">
        Creare Factură
      </button>
    </div>

    <div *ngIf="billPopupVisible" class="popup">
      <h2>Creare Factură</h2>
      <form [formGroup]="billForm" (ngSubmit)="generateBill()">
        <input formControlName="customerName" placeholder="Nume client" />
        <input formControlName="customerPhone" placeholder="Telefon" />
        <input formControlName="customerAddress" placeholder="Adresă" />
        <select formControlName="paymentMethod" required>
          <option value="" disabled selected hidden>Metoda de plată</option>
          <option value="cash">Cash</option>
          <option value="paypal">Paypal</option>
          <option value="card">Card</option>
        </select>

        <div class="total">
          <p>Subtotal: €{{ subTotal.toFixed(2) }}</p>
          <p>Taxă: €{{ (subTotal * 0.1).toFixed(2) }}</p>
          <h3>Total: €{{ (subTotal + subTotal * 0.1).toFixed(2) }}</h3>
        </div>

        <button type="submit" mat-raised-button color="primary">
          Generează factura
        </button>
        <button type="button" mat-button (click)="closeBillPopup()">
          Anulează
        </button>
      </form>
    </div>
  </div>
</div>

// MERN/frontend/src/pages/cart/Cart.jsx
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import LayoutApp from "../../components/Layout/Layout";
import {
  DeleteOutlined,
  PlusCircleOutlined,
  MinusCircleOutlined,
} from "@ant-design/icons";
import { Button, Form, Input, message, Modal, Select, Table } from "antd";
import { useNavigate } from "react-router-dom";
import axios from "axios";

const Cart = () => {
  const [subTotal, setSubTotal] = useState(0);
  const [billPopUp, setBillPopUp] = useState(false);

  const dispatch = useDispatch();
  const navigate = useNavigate();

  const { cartItems } = useSelector((state) => state.rootReducer);

  // Calculează subtotalul
  useEffect(() => {
    const temp = cartItems.reduce(
      (total, product) => total + product.price * product.quantity,
      0
    );
    setSubTotal(temp);
  }, [cartItems]);

  // Funcții de incrementare, decrementare și ștergere produse
  const handlerIncrement = (record) => {
    dispatch({
      type: "UPDATE_CART",
      payload: { ...record, quantity: record.quantity + 1 },
    });
  };

  const handlerDecrement = (record) => {
    if (record.quantity > 1) {
      dispatch({
        type: "UPDATE_CART",
        payload: { ...record, quantity: record.quantity - 1 },
      });
    }
  };

  const handlerDelete = (record) => {
    dispatch({
      type: "DELETE_FROM_CART",
      payload: record,
    });
  };

  // Coloanele pentru tabel
  const columns = [
    {
      title: "Nume",
      dataIndex: "name",
    },
    {
      title: "Imagine",
      dataIndex: "image",
      render: (image, record) => (
        <img src={image} alt={record.name} height={60} width={60} />
      ),
    },
    {
      title: "Preț",
      dataIndex: "price",
      render: (price) => {
        return price ? `${price} €` : "N/A";
      },
    },
    {
      title: "Cantitate",
      dataIndex: "_id",
      render: (id, record) => (
        <div>
          <MinusCircleOutlined
            className='cart-minus'
            onClick={() => handlerDecrement(record)}
          />
          <strong className='cart-quantity'>{record.quantity}</strong>
          <PlusCircleOutlined
            className='cart-plus'
            onClick={() => handlerIncrement(record)}
          />
        </div>
      ),
    },
    {
      title: "Acțiune",
      dataIndex: "_id",
      render: (id, record) => (
        <DeleteOutlined
          className='cart-action'
          onClick={() => handlerDelete(record)}
        />
      ),
    },
  ];

  // Funcția pentru generarea facturii
  const handlerSubmit = async (value) => {
    try {
      const user = JSON.parse(localStorage.getItem("auth"));

      if (!user || !user.id) {
        message.error("Nu s-a găsit utilizatorul autentificat.");
        return;
      }

      const tax = Number(((subTotal / 100) * 10).toFixed(2));
      const totalAmount = Number((subTotal + tax).toFixed(2));

      const newObject = {
        ...value,
        cartItems,
        subTotal,
        tax,
        totalAmount,
        userId: user.id,
      };

      const response = await axios.post("/api/bills/addbills", newObject);

      message.success("Factură generată cu succes!");

      dispatch({
        type: "CLEAR_CART",
      });

      // Verifică rolul utilizatorului și redirecționează în funcție de acesta
      if (user.role === "admin") {
        navigate("/bills"); // Adminul merge la pagina `bills`
      } else {
        navigate("/your-bills"); // Utilizatorul obișnuit merge la `your_bills`
      }
    } catch (error) {
      const errorMsg =
        error.response?.data?.message || "Eroare la generarea facturii!";
      message.error(errorMsg);
      console.error("Eroare server:", error.response || error);
    }
  };

  return (
    <LayoutApp>
      <h2>Coșul tău</h2>
      {cartItems.length === 0 ? (
        <div>
          <h2 style={{ marginTop: "20px", color: "#0099ff" }}>
            Coșul tău este gol!
          </h2>
          <Button onClick={() => navigate("/")} className='add-new'>
            Mergi la produse
          </Button>
        </div>
      ) : (
        <>
          <Table dataSource={cartItems} columns={columns} bordered />
          <div className='subTotal'>
            <h2>
              Sub Total: <span>€ {subTotal.toFixed(2)}</span>
            </h2>
            <Button onClick={() => setBillPopUp(true)} className='add-new'>
              Creare Factură
            </Button>
          </div>
          <Modal
            title='Creare Factură'
            open={billPopUp}
            onCancel={() => setBillPopUp(false)}
            footer={null}>
            <Form layout='vertical' onFinish={handlerSubmit}>
              <Form.Item
                name='customerName'
                label='Numele clientului'
                rules={[
                  { required: true, message: "Numele clientului este necesar" },
                ]}>
                <Input />
              </Form.Item>
              <Form.Item
                name='customerPhone'
                label='Numărul de telefon'
                rules={[
                  {
                    required: true,
                    message: "Numărul de telefon este necesar",
                  },
                ]}>
                <Input />
              </Form.Item>
              <Form.Item
                name='customerAddress'
                label='Adresa clientului'
                rules={[
                  {
                    required: true,
                    message: "Adresa clientului este necesară",
                  },
                ]}>
                <Input />
              </Form.Item>
              <Form.Item
                name='paymentMethod'
                label='Metoda de plată'
                rules={[
                  { required: true, message: "Metoda de plată este necesară" },
                ]}>
                <Select>
                  <Select.Option value='cash'>Cash</Select.Option>
                  <Select.Option value='paypal'>Paypal</Select.Option>
                  <Select.Option value='Card'>Card</Select.Option>
                </Select>
              </Form.Item>
              <div className='total'>
                <span>SubTotal: €{subTotal.toFixed(2)}</span>
                <br />
                <span>Taxă: €{((subTotal / 100) * 10).toFixed(2)}</span>
                <h3>
                  Total: €
                  {(
                    Number(subTotal) +
                    Number(((subTotal / 100) * 10).toFixed(2))
                  ).toFixed(2)}
                </h3>
              </div>
              <div className='form-btn-add'>
                <Button htmlType='submit' className='add-new'>
                  Generează factura
                </Button>
              </div>
            </Form>
          </Modal>
        </>
      )}
    </LayoutApp>
  );
};

export default Cart;
