// MEAN/frontend/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ProductCardComponent } from '../../components/product-card/product-card.component';
import { NgFor } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';

interface Product {
  _id: string;
  name: string;
  image: string;
  price: number;
  category: string;
  description: string;
  stock: number;
}

@Component({
  standalone: true,
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  imports: [ProductCardComponent, NgFor, HttpClientModule],
})
export class HomeComponent implements OnInit {
  productData: Product[] = [];
  selectedCategory: string = 'Canon';

  categories = [
    {
      name: 'Canon',
      imageUrl:
        'https://i.pinimg.com/originals/fc/bc/3c/fcbc3cb041bcbfdbef21aeb370517801.png',
    },
    {
      name: 'Nikon',
      imageUrl:
        'https://w7.pngwing.com/pngs/1013/525/png-transparent-nikon-d40-logo-camera-text-photography-logo.png',
    },
    {
      name: 'Sony',
      imageUrl:
        'https://e7.pngegg.com/pngimages/262/162/png-clipart-sony-sony.png',
    },
  ];

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.http
      .get<Product[]>('http://localhost:5000/api/products/getproducts')
      .subscribe({
        next: (data) => {
          console.log(data);
          this.productData = data;
        },
      });
  }

  selectCategory(category: string): void {
    this.selectedCategory = category;
  }

  get filteredProducts(): Product[] {
    return this.productData.filter((p) => p.category === this.selectedCategory);
  }
}

<div class="category" style="padding-bottom: 50px; padding-top: 20px">
  <div
    *ngFor="let category of categories"
    class="categoryFlex"
    [class.category-active]="selectedCategory === category.name"
    (click)="selectCategory(category.name)"
  >
    <h3 class="categoryName">{{ category.name }}</h3>
    <img
      [src]="category.imageUrl"
      [alt]="category.name"
      height="60"
      width="60"
    />
  </div>
</div>

<h2 style="margin-bottom: 50px; padding-left: 100px; padding-bottom: 20px">
  Home
</h2>

<div class="row" style="padding: 20px 40px">
  <div
    class="col-xs-12 col-sm-6 col-md-4 col-lg-3"
    *ngFor="let product of filteredProducts"
  >
    <app-product-card [product]="product"></app-product-card>
  </div>
</div>

// MERN/frontend/src/pages/home/Home.jsx
import React, { useState, useEffect } from "react";
import axios from "axios";
import LayoutApp from "../../components/Layout/Layout";
import { Row, Col } from "antd";
import Product from "../../components/ProductCard/ProductCard";
import { useDispatch } from "react-redux";

const Home = () => {
  const dispatch = useDispatch();

  const [productData, setProductData] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState("Canon");
  const categories = [
    {
      name: "Canon",
      imageUrl:
        "https://i.pinimg.com/originals/fc/bc/3c/fcbc3cb041bcbfdbef21aeb370517801.png",
    },
    {
      name: "Nikon",
      imageUrl:
        "https://w7.pngwing.com/pngs/1013/525/png-transparent-nikon-d40-logo-camera-text-photography-logo.png",
    },
    {
      name: "Sony",
      imageUrl:
        "https://e7.pngegg.com/pngimages/262/162/png-clipart-sony-sony.png",
    },
  ];

  useEffect(() => {
    const getAllProducts = async () => {
      try {
        dispatch({
          type: "SHOW_LOADING",
        });
        const { data } = await axios.get("/api/products/getproducts");
        setProductData(data);
        dispatch({
          type: "HIDE_LOADING",
        });
        console.log(data);
      } catch (error) {
        console.log(error);
      }
    };
    getAllProducts();
  }, [dispatch]);

  return (
    <LayoutApp>
      <div className='category'>
        {categories.map((category) => (
          <div
            key={category.name}
            className={`categoryFlex ${
              selectedCategory === category.name && "category-active"
            }`}
            onClick={() => setSelectedCategory(category.name)}>
            <h3 className='categoryName'>{category.name}</h3>
            <img
              src={category.imageUrl}
              alt={category.name}
              height={60}
              width={60}
            />
          </div>
        ))}
      </div>
      <h2 style={{ marginBottom: "50px", marginLeft: "50px" }}>Home</h2>
      <Row>
        {productData
          .filter((i) => i.category === selectedCategory)
          .map((product) => (
            <Col xs={24} sm={6} md={12} lg={6}>
              <Product key={product.id} product={product} />
            </Col>
          ))}
      </Row>
    </LayoutApp>
  );
};

export default Home;
