// MEAN/frontend/src/app/pages/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient, HttpClientModule } from '@angular/common/http';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
  imports: [ReactiveFormsModule, HttpClientModule],
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup;
  loading = false;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.registerForm = this.fb.group({
      name: ['', Validators.required],
      userId: ['', Validators.required],
      password: ['', Validators.required],
    });

    // ✅ Verificare că rulează în browser
    if (typeof window !== 'undefined') {
      const auth = localStorage.getItem('auth');
      if (auth) {
        this.router.navigate(['/']);
      }
    }
  }

  goToLogin() {
    this.router.navigate(['/login']);
  }

  onSubmit(): void {
    if (this.registerForm.invalid) return;

    this.loading = true;

    this.http
      .post<any>('/api/users/register', this.registerForm.value)
      .subscribe({
        next: () => {
          this.loading = false;
          alert('Utilizator înregistrat cu succes!');
          this.router.navigate(['/login']);
        },
        error: (err) => {
          this.loading = false;
          alert('Eroare la înregistrare!');
          console.error(err);
        },
      });
  }
}

<div class="form">
  <h2>Camera Shop</h2>
  <p>Înregistrează-te</p>
  <div class="form-group">
    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
      <label for="name">Nume</label>
      <input id="name" type="text" formControlName="name" />
      <br />

      <label for="userId">ID Utilizator</label>
      <input id="userId" type="text" formControlName="userId" />
      <br />

      <label for="password">Parola</label>
      <input id="password" type="password" formControlName="password" />
      <br />

      <div class="form-btn-add">
        <button type="submit" [disabled]="loading">Înregistrează-te</button>
        <button mat-button (click)="goToLogin()">Autentifică-te aici!</button>
      </div>
    </form>
  </div>
</div>

// MERN/frontend/src/register/Register.jsx
import { Form, Input, Button, message } from "antd";
import FormItem from "antd/lib/form/FormItem";
import React, { useEffect } from "react";
import { useDispatch } from "react-redux";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";

const Register = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const handlerSubmit = async (value) => {
    try {
      dispatch({
        type: "SHOW_LOADING",
      });
      await axios.post("/api/users/register", value);
      message.success("Utilizator înregistrat cu succes!");
      navigate("/login");
      dispatch({
        type: "HIDE_LOADING",
      });
    } catch (error) {
      dispatch({
        type: "HIDE_LOADING",
      });
      message.error("Error!");
      console.log(error);
    }
  };

  useEffect(() => {
    if (localStorage.getItem("auth")) {
      localStorage.getItem("auth");
      navigate("/");
    }
  }, [navigate]);

  return (
    <div className='form'>
      <h2>Camera Shop</h2>
      <p>Inregistrează-te</p>
      <div className='form-group'>
        <Form layout='vertical' onFinish={handlerSubmit}>
          <FormItem name='name' label='Nume'>
            <Input />
          </FormItem>
          <FormItem name='userId' label='ID Utilizator'>
            <Input />
          </FormItem>
          <FormItem name='password' label='Parola'>
            <Input type='password' />
          </FormItem>
          <div className='form-btn-add'>
            <Button htmlType='submit' className='add-new'>
              Inregistrează-te
            </Button>
            <Link className='form-other' to='/login'>
              Autentifică-te aici!
            </Link>
          </div>
        </Form>
      </div>
    </div>
  );
};

export default Register;
