// MERN/frontend/src/login/Login.jsx
import { Button, Form, Input, message } from "antd";
import FormItem from "antd/es/form/FormItem";
import React from "react";
import { useDispatch } from "react-redux";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { useEffect } from "react";

const Login = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const handlerSubmit = async (value) => {
    //console.log(value);
    try {
      dispatch({
        type: "SHOW_LOADING",
      });
      const res = await axios.post("/api/users/login", value);
      console.log("Răspuns server:", res.data);
      dispatch({
        type: "HIDE_LOADING",
      });
      message.success("Utilizator autentificat cu succes!");
      localStorage.setItem(
        "auth",
        JSON.stringify({
          token: res.data.token,
          role: res.data.user.role,
          id: res.data.user.id,
          name: res.data.user.name,
        })
      );
      navigate("/");
    } catch (error) {
      dispatch({
        type: "HIDE_LOADING",
      });
      message.error("Error!");
      console.log(error);
    }
  };

  useEffect(() => {
    if (localStorage.getItem("auth")) {
      localStorage.getItem("auth");
      navigate("/");
    }
  }, [navigate]);

  return (
    <div className='form'>
      <h2>Camera Shop</h2>
      <p>Autentifică-te</p>
      <div className='form-group'>
        <Form layout='vertical' onFinish={handlerSubmit}>
          <FormItem name='userId' label='ID Utilizator'>
            <Input />
          </FormItem>
          <FormItem name='password' label='Parola'>
            <Input type='password' />
          </FormItem>
          <div className='form-btn-add'>
            <Button htmlType='submit' className='add-new'>
              Autentifică-te
            </Button>
            <Link className='form-other' to='/register'>
              Inregistrează-te aici!
            </Link>
          </div>
        </Form>
      </div>
    </div>
  );
};

export default Login;

// MEAN/frontend/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient, HttpClientModule } from '@angular/common/http';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  imports: [ReactiveFormsModule, HttpClientModule],
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  loading = false;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      userId: ['', Validators.required],
      password: ['', Validators.required],
    });

    if (typeof window !== 'undefined') {
      const auth = localStorage.getItem('auth');
      if (auth) {
        this.router.navigate(['/']);
      }
    }
  }

  goToRegister() {
    this.router.navigate(['/register']);
  }

  onSubmit(): void {
    if (this.loginForm.invalid) return;

    this.loading = true;

    this.http.post<any>('/api/users/login', this.loginForm.value).subscribe({
      next: (res) => {
        this.loading = false;
        alert('Utilizator autentificat cu succes!');
        localStorage.setItem(
          'auth',
          JSON.stringify({
            token: res.token,
            role: res.user.role,
            id: res.user.id,
            name: res.user.name,
          })
        );
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.loading = false;
        alert('Eroare la autentificare!');
        console.error(err);
      },
    });
  }
}

<div class="form">
  <h2>Camera Shop</h2>
  <p>Autentifică-te</p>
  <div class="form-group">
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <label for="userId">ID Utilizator</label>
      <input id="userId" type="text" formControlName="userId" />
      <br />
      <label for="password">Parola</label>
      <input id="password" type="password" formControlName="password" />
      <br />
      <div class="form-btn-add">
        <button type="submit" [disabled]="loading">Autentifică-te</button>
        <button mat-button (click)="goToRegister()">
          Înregistrează-te aici!
        </button>
      </div>
    </form>
  </div>
</div>
