// MEAN/frontend/src/app/pages/bills/your-bills.component.ts
import { Component, OnInit } from '@angular/core';
import { BillsService } from '../../services/bills.service';
import { MatDialog } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { jwtDecode } from 'jwt-decode';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule } from '@angular/material/dialog';
import { BillDetailsDialogComponent } from '../../components/bill-dialog/bill-details-dialog.component';
import { MatIcon, MatIconModule } from '@angular/material/icon';
import { MatSpinner } from '@angular/material/progress-spinner';
import { MatTableModule } from '@angular/material/table';
import { PurchasedService } from '../../services/purchased.service';

@Component({
  selector: 'app-your-bills',
  templateUrl: './your-bills.component.html',
  styleUrls: ['./your-bills.component.css'],
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatDialogModule,
    MatIconModule,
    MatIcon,
    MatSpinner,
    MatTableModule,
  ],
})
export class YourBillsComponent implements OnInit {
  billsData: any[] = [];
  loading = false;
  purchasedItems: any[] = [];

  displayedColumns: string[] = [
    '_id',
    'customerName',
    'customerPhone',
    'customerAddress',
    'subTotal',
    'tax',
    'totalAmount',
    'actions',
  ];

  constructor(
    private billsService: BillsService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar,
    private purchasedService: PurchasedService
  ) {}

  ngOnInit(): void {
    if (typeof window !== 'undefined') {
      this.getUserBills();
    } else {
    }
  }
  getUserBills(): void {
    if (typeof window !== 'undefined' && window.localStorage) {
      const authStr = localStorage.getItem('auth');
      if (!authStr) {
        console.warn('Nu există date de autentificare în localStorage');
        return;
      }

      let authData;
      try {
        authData = JSON.parse(authStr);
      } catch (e) {
        console.error('Datele din localStorage nu pot fi parsate', e);
        return;
      }

      const token = authData.token;
      const userId = authData.id;

      if (!token || !userId) {
        console.warn('Token-ul sau userId nu au fost găsite.');
        return;
      }

      const decodedToken: any = jwtDecode(token);
      const decodedUserId = decodedToken.id;

      if (userId !== decodedUserId) {
        console.warn(
          'UserId-ul din localStorage nu se potrivește cu cel din token.'
        );
        return;
      }

      this.loading = true;

      this.billsService.getBillsByUserId(decodedUserId).subscribe({
        next: (data) => {
          this.billsData = data;
          const allItems = data.flatMap((bill: any) => bill.cartItems || []);
          this.purchasedItems = allItems;
          this.purchasedService.setItems(allItems);
          this.loading = false;
        },
        error: (err) => {
          this.snackBar.open('Eroare la obținerea facturilor!', 'Închide', {
            duration: 3000,
          });
          console.error(err);
          this.loading = false;
        },
      });
    } else {
      console.warn('localStorage nu este disponibil.');
    }
  }

  showBillDetails(bill: any): void {
    this.dialog.open(BillDetailsDialogComponent, {
      width: '400px',
      data: bill,
    });
  }

  deleteBill(bill: any): void {
    this.billsService.deleteBill(bill._id).subscribe({
      next: () => {
        this.snackBar.open('Factura a fost ștearsă cu succes!', 'OK', {
          duration: 3000,
        });

        this.purchasedItems = this.purchasedItems.filter(
          (item) =>
            !bill.cartItems.some((cartItem: any) => cartItem._id === item._id)
        );

        this.getUserBills();
      },
      error: (err) => {
        this.snackBar.open('Eroare la ștergerea facturii!', 'Închide', {
          duration: 3000,
        });
        console.error(err);
      },
    });
  }
}

<div class="product-container">
  <h2 class="title" style="margin-bottom: 40px">Facturile tale</h2>

  <table
    mat-table
    [dataSource]="billsData"
    class="mat-elevation-z8 product-table"
    *ngIf="!loading"
  >
    <!-- ID -->
    <ng-container matColumnDef="_id">
      <th mat-header-cell *matHeaderCellDef>ID</th>
      <td mat-cell *matCellDef="let bill">{{ bill._id }}</td>
    </ng-container>

    <!-- Nume client -->
    <ng-container matColumnDef="customerName">
      <th mat-header-cell *matHeaderCellDef>Nume client</th>
      <td mat-cell *matCellDef="let bill">{{ bill.customerName }}</td>
    </ng-container>

    <!-- Telefon -->
    <ng-container matColumnDef="customerPhone">
      <th mat-header-cell *matHeaderCellDef>Număr de telefon</th>
      <td mat-cell *matCellDef="let bill">{{ bill.customerPhone }}</td>
    </ng-container>

    <!-- Adresa -->
    <ng-container matColumnDef="customerAddress">
      <th mat-header-cell *matHeaderCellDef>Adresă</th>
      <td mat-cell *matCellDef="let bill">{{ bill.customerAddress }}</td>
    </ng-container>

    <!-- Sub Total -->
    <ng-container matColumnDef="subTotal">
      <th mat-header-cell *matHeaderCellDef>Sub Total</th>
      <td mat-cell *matCellDef="let bill">{{ bill.subTotal }}</td>
    </ng-container>

    <!-- Taxe -->
    <ng-container matColumnDef="tax">
      <th mat-header-cell *matHeaderCellDef>Taxe</th>
      <td mat-cell *matCellDef="let bill">{{ bill.tax }}</td>
    </ng-container>

    <!-- Total -->
    <ng-container matColumnDef="totalAmount">
      <th mat-header-cell *matHeaderCellDef>Valoare totală</th>
      <td mat-cell *matCellDef="let bill">{{ bill.totalAmount }}</td>
    </ng-container>

    <!-- Acțiuni -->
    <ng-container matColumnDef="actions">
      <th mat-header-cell *matHeaderCellDef>Acțiuni</th>
      <td mat-cell *matCellDef="let bill">
        <button mat-icon-button color="primary" (click)="showBillDetails(bill)">
          <mat-icon>visibility</mat-icon>
        </button>
        <button mat-icon-button color="warn" (click)="deleteBill(bill)">
          <mat-icon>delete</mat-icon>
        </button>
      </td>
    </ng-container>

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>

  <div class="spinner-container" *ngIf="loading">
    <mat-spinner></mat-spinner>
  </div>
</div>

// MERN/frontend/src/pages/bills/YourBills.jsx
import { Modal, Table, message } from "antd";
import axios from "axios";
import React, { useEffect, useState, useRef } from "react";
import { EyeOutlined, DeleteOutlined } from "@ant-design/icons";
import { useDispatch, useSelector } from "react-redux";
import LayoutApp from "../../components/Layout/Layout";
import { jwtDecode } from "jwt-decode";

const YourBills = () => {
  const dispatch = useDispatch(); // Folosim dispatch pentru a actualiza Redux
  const { purchasedItems } = useSelector((state) => state.rootReducer); // Obținem purchasedItems din Redux store
  const componentRef = useRef();

  const [billsData, setBillsData] = useState([]); // Stocăm datele facturilor
  const [popModal, setPopModal] = useState(false); // Controlează modalul
  const [selectedBill, setSelectedBill] = useState(null); // Factura selectată
  const [loading, setLoading] = useState(false); // Statusul de încărcare

  // Funcția pentru obținerea facturilor
  const getUserBills = async () => {
    try {
      // Obține token-ul și userId din localStorage
      const authData = JSON.parse(localStorage.getItem("auth"));
      const token = authData ? authData.token : null;
      const userId = authData ? authData.id : null; // Obținem și userId-ul din localStorage

      if (!token || !userId) {
        console.log("Token-ul sau userId nu au fost găsite.");
        return;
      }

      // Decodează token-ul pentru a obține userId (dacă nu l-am obținut deja)
      const decodedToken = jwtDecode(token);
      const decodedUserId = decodedToken.id;

      // Dacă userId din token nu este același cu cel din localStorage, nu continuăm
      if (userId !== decodedUserId) {
        console.log(
          "UserId-ul din localStorage nu se potrivește cu cel din token."
        );
        return;
      }

      console.log("User ID obținut din token:", decodedUserId);

      // Trimite cererea pentru a obține facturile
      const response = await axios.get(`/api/bills/getbills/${decodedUserId}`);
      console.log("Facturi primite:", response.data);

      // Salvează datele în state
      setBillsData(response.data);

      // Adăugăm produsele cumpărate în Redux store
      const productsFromBills = response.data.flatMap((bill) => bill.cartItems);
      dispatch({ type: "SET_PURCHASED_ITEMS", payload: productsFromBills });
    } catch (error) {
      console.error("Eroare la obținerea facturilor:", error);
      message.error("Eroare la obținerea facturilor!");
    }
  };

  // Funcția pentru ștergerea unei facturi
  const handlerDelete = async (record) => {
    try {
      const response = await axios.delete(
        `/api/bills/deletebills/${record._id}`
      );
      message.success("Factura a fost ștearsă cu succes!");

      // Ștergem produsele asociate facturii din purchasedItems din Redux
      const updatedPurchasedItems = purchasedItems.filter(
        (item) =>
          !record.cartItems.some((cartItem) => cartItem._id === item._id)
      );

      dispatch({ type: "SET_PURCHASED_ITEMS", payload: updatedPurchasedItems });

      // Actualizăm lista de facturi
      getUserBills();
    } catch (error) {
      message.error("Eroare la ștergerea facturii!");
      console.error(error);
    }
  };

  // Această funcție se apelează doar atunci când componenta se montează
  useEffect(() => {
    getUserBills();
  }, []); // La început, obținem facturile pentru utilizatorul curent

  const columns = [
    {
      title: "ID",
      dataIndex: "_id",
    },
    {
      title: "Nume client",
      dataIndex: "customerName",
    },
    {
      title: "Număr de telefon",
      dataIndex: "customerPhone",
    },
    {
      title: "Adresa",
      dataIndex: "customerAddress",
    },
    {
      title: "Sub Total",
      dataIndex: "subTotal",
    },
    {
      title: "Taxe",
      dataIndex: "tax",
    },
    {
      title: "Valoare totală",
      dataIndex: "totalAmount",
    },
    {
      title: "Acțiuni",
      dataIndex: "_id",
      render: (id, record) => (
        <div>
          <EyeOutlined
            className='cart-edit eye'
            onClick={() => {
              setSelectedBill(record);
              setPopModal(true);
            }}
          />
          <DeleteOutlined
            className='cart-action delete'
            style={{ marginLeft: "20px" }}
            onClick={() => handlerDelete(record)}
          />
        </div>
      ),
    },
  ];

  return (
    <LayoutApp>
      <h2>Facturile tale</h2>

      {/* Afișează tabelul de facturi */}
      <Table
        dataSource={billsData.map((bill) => ({ ...bill, key: bill._id }))}
        columns={columns}
        bordered
        loading={loading} // Arată indicatorul de încărcare când se fac cereri API
      />

      {/* Modalul cu detaliile facturii */}
      {popModal && selectedBill && (
        <Modal
          title='Detalii factură'
          width={400}
          pagination={false}
          open={popModal}
          onCancel={() => setPopModal(false)}
          footer={false}>
          <div className='card' ref={componentRef}>
            <div className='cardHeader'>
              <h2 className='logo'>Camera Shop</h2>
              <span>
                Număr de telefon: <b>+40/0000000</b>
              </span>
              <span>
                Adresa: <b>Oradea</b>
              </span>
            </div>

            <div className='cardBody'>
              <div className='group'>
                <span>Numele clientului:</span>
                <span>
                  <b>{selectedBill.customerName}</b>
                </span>
              </div>
              <div className='group'>
                <span>Numărul de telefon:</span>
                <span>
                  <b>{selectedBill.customerPhone}</b>
                </span>
              </div>
              <div className='group'>
                <span>Adresa clientului:</span>
                <span>
                  <b>{selectedBill.customerAddress}</b>
                </span>
              </div>
              <div className='group'>
                <span>Valoare totală</span>
                <span>
                  <b>€{selectedBill.totalAmount}</b>
                </span>
              </div>
            </div>

            <div className='cardFooter'>
              <h4>Comanda ta</h4>
              {selectedBill.cartItems.map((product, index) => (
                <div key={index} className='footerCard'>
                  <div className='group'>
                    <span>Produs:</span>
                    <span>
                      <b>{product.name}</b>
                    </span>
                  </div>
                  <div className='group'>
                    <span>Cantitate:</span>
                    <span>
                      <b>{product.quantity}</b>
                    </span>
                  </div>
                  <div className='group'>
                    <span>Preț:</span>
                    <span>
                      <b>€{product.price}</b>
                    </span>
                  </div>
                </div>
              ))}

              <div className='footerCardTotal'>
                <div className='group'>
                  <h3>Total:</h3>
                  <h3>
                    <b>€{selectedBill.totalAmount}</b>
                  </h3>
                </div>
              </div>

              <div className='footerThanks'>
                <span>Mulțumim că ați comandat de la noi!</span>
              </div>
            </div>
          </div>
        </Modal>
      )}
    </LayoutApp>
  );
};

export default YourBills;
